### ISSUE TITLE
Peer review by MrSampy

### ISSUE THREAD

**Issue by MrSampy** [MytsV/pixel-toons-editor#19]
1.This function can be replaced by destructuring assignment
https://github.com/MytsV/pixel-toons-editor/blob/a3c7e304b4272ecf7e315e86a5905bbfd355d735/public/scripts/utilities/bmp_encoder.js#L226-L230
```js
[a, b] = [b, a];
```
2. It can be transformed in arrow function
https://github.com/MytsV/pixel-toons-editor/blob/a3c7e304b4272ecf7e315e86a5905bbfd355d735/public/scripts/utilities/image.js#L45-L47

3.This function can be transformed in arrow one, using ternary operator
https://github.com/MytsV/pixel-toons-editor/blob/a3c7e304b4272ecf7e315e86a5905bbfd355d735/public/scripts/core/canvas_renderer.js#L131-L138

**Comment by MytsV** [comment]
Thank you! Fixed everything I could
Currently the fixes are in gif-encoder branch
